name: Build Release 

on: 
  push:
    tags:
     - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test
    - name: Publish Windows app
      run: dotnet publish BankKata --configuration Release --runtime win-x64 --self-contained false --framework netcoreapp3.1
    - name: Publish Linux app
      run: dotnet publish BankKata --configuration Release --runtime linux-x64 --self-contained false --framework netcoreapp3.1
    - name: Create Windows Artifact
      uses: actions/upload-artifact@v1
      with:
        name: BankKata-win
        path: /home/runner/work/BankingKataCS/BankingKataCS/BankKata/bin/Release/netcoreapp3.1/win-x64/publish/
    - name: Create Linux Artifact
      uses: actions/upload-artifact@v1
      with:
        name: BankKata-linux
        path: /home/runner/work/BankingKataCS/BankingKataCS/BankKata/bin/Release/netcoreapp3.1/linux-x64/publish/
